### ISSUE TITLE
No module named 'MinTree

### ISSUE THREAD

**Issue by Mantj** [rgmining/fraudar#33]
Hi, I install fraudar  successfully by using code below:
`pip install --upgrade rgmining-fraudar`

But when I IMPORT FRAUDAR, I ran into a ERROR:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/fraudar/__init__.py", line 41, in <module>
    from fraudar.graph import ReviewGraph
  File "/opt/conda/lib/python3.6/site-packages/fraudar/graph.py", line 31, in <module>
    from fraudar.export import greedy
  File "/opt/conda/lib/python3.6/site-packages/fraudar/export/greedy.py", line 53, in <module>
    from MinTree import MinTree
ModuleNotFoundError: No module named 'MinTree'`

Could anyone help me?

**Comment by jkawamoto** [comment]
It looks like you may be using an older version.
Please check if you have the latest version installed by running `pip install rgmining-fraudar==0.7.3` or verify if 'rgmining-fraudar 0.7.3' is installed using `pip list`.

**Comment by Mantj** [comment]
I solved this problem
I change my python version from 3.6 to 3.9, it solved.
